# Generated by Django 3.1.5 on 2021-01-10 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=150)),
                ('minit', models.CharField(max_length=150)),
                ('lname', models.CharField(max_length=150)),
                ('bdate', models.DateField(verbose_name='birth date')),
                ('address', models.CharField(max_length=200)),
                ('gender', models.CharField(choices=[('ml', 'male'), ('fm', 'female')], default=1, max_length=10)),
                ('salary', models.FloatField()),
            ],
        ),
    ]
