# Generated by Django 3.1.5 on 2021-01-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_auto_20210117_1419'),
        ('depart_locations', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='depart_location',
            options={'verbose_name_plural': 'Department Location'},
        ),
        migrations.AddField(
            model_name='depart_location',
            name='dlocation',
            field=models.CharField(default=None, max_length=200, verbose_name='Department Location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='depart_location',
            name='dnumber',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='department.department'),
            preserve_default=False,
        ),
    ]
