# Generated by Django 3.1.5 on 2021-01-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('project', '0001_initial'),
        ('employee', '0003_auto_20210117_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='works_on',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Hours', models.CharField(max_length=200)),
                ('Essn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
                ('Pno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.project', verbose_name='Project Number')),
            ],
        ),
    ]
