# Generated by Django 3.1.5 on 2021-01-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('department', '0003_auto_20210117_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('pnumber', models.AutoField(primary_key=True, serialize=False, verbose_name='Project Number')),
                ('pname', models.CharField(max_length=150, verbose_name='Project Name')),
                ('plocation', models.CharField(max_length=200, verbose_name='Project Location')),
                ('dnumber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='department.department')),
            ],
        ),
    ]
