# Generated by Django 3.1.5 on 2021-01-17 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('employee', '0003_auto_20210117_1419'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependent',
            fields=[
                ('Dependent_name', models.CharField(max_length=250, primary_key=True, serialize=False, verbose_name='Dependent Name')),
                ('gender', models.CharField(choices=[('M', 'male'), ('F', 'female')], default=1, max_length=10)),
                ('Relationship', models.CharField(max_length=250)),
                ('bdate', models.DateField(verbose_name='birth date')),
                ('Essn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.employee')),
            ],
        ),
    ]
