# Generated by Django 3.1.5 on 2021-01-17 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_department_mgr_ssn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='dname',
            field=models.CharField(max_length=150, verbose_name='Department Name'),
        ),
        migrations.AlterField(
            model_name='department',
            name='dnumber',
            field=models.AutoField(primary_key=True, serialize=False, verbose_name='Department Number'),
        ),
    ]
